DELIMITER $$
CREATE FUNCTION `IS_DECEASED`(`FIELD_VALUE` INT) RETURNS bool
BEGIN
  DECLARE flag bool DEFAULT false;

  SELECT  EXISTS(
  SELECT 
    * 
  FROM 
    `DECEASED`
  WHERE 
    `id` = FIELD_VALUE) INTO flag;
  RETURN flag;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER before_patient_delete 
    BEFORE DELETE ON PATIENT
    FOR EACH ROW BEGIN
		IF (IS_DECEASED(OLD.id)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'This record is read-only';
		END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER before_patient_update
    BEFORE DELETE ON PATIENT
    FOR EACH ROW BEGIN
		IF (IS_DECEASED(OLD.id)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'This record is read-only';
		END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER before_record_delete 
    BEFORE DELETE ON MEDICAL_RECORD
    FOR EACH ROW BEGIN
		IF (IS_DECEASED(OLD.patient)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'This record is read-only';
		END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER before_record_update 
    BEFORE UPDATE ON MEDICAL_RECORD
    FOR EACH ROW BEGIN
		IF (IS_DECEASED(OLD.patient)) THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'This record is read-only';
		END IF;
END$$
DELIMITER ;