CREATE TABLE `PATIENT` (
	id INT NOT NULL PRIMARY KEY, 
	firstname VARCHAR(20) NOT NULL,
    relative_email TEXT NOT NULL,
	lastname VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
	phonenumber TEXT NOT NULL, 
	birthday DATE NOT NULL, 
	gender ENUM('M', 'F') NOT NULL
);

CREATE TABLE DECEASED(
    id INT NOT NULL PRIMARY KEY
);  

CREATE TABLE REQUEST(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    patient INT NOT NULL,
    `date` DATE NOT NULL,
    content TEXT NOT NULL
);  

CREATE TABLE `USER` (
	id INT NOT NULL PRIMARY KEY, 
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
    email VARCHAR(60) NOT NULL, 
	phonenumber TEXT NOT NULL,
    username VARCHAR(20) NOT NULL,
    `password` TEXT NOT NULL,
    `type` ENUM ('CLINICAL_STAFF','RECEPTIONIST','MEDICAL_RECORD_STAFF','HEALTH_SERVICE_MANAGEMENT')
);

CREATE TABLE `COMMENT` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	content TEXT NOT NULL,
    patient	INT NOT NULL,
    clinician INT NOT NULL,
    `date` DATE NOT NULL
);

CREATE TABLE `MEDICINE` (
    `name` VARCHAR(15) NOT NULL PRIMARY KEY,
	description TEXT NOT NULL
);

CREATE TABLE `SIDE_EFFECT` (
	medicine VARCHAR(15) NOT NULL, 
	side_effect TEXT NOT NULL
);


CREATE TABLE `CONSULTANT` (
	clinician INT NOT NULL, 
	patient INT NOT NULL
);

CREATE TABLE `WARNING_OVERRULED` (
	clinician INT NOT NULL, 
	warning TEXT NOT NULL,
    `date` DATE NOT NULL
);


CREATE TABLE `MEDICAL_RECORD` (
	patient INT NOT NULL,
    last_updated DATE NOT NULL,
    `status` ENUM ('DANGEROUS','NOT_DANGEROUS') NOT NULL
);

CREATE TABLE `TREATMENT` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`condition` TEXT NOT NULL,
    medicine VARCHAR(15) NOT NULL,
    quantity INT NOT NULL
);


CREATE TABLE `INCIDENT` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	patient INT NOT NULL,
    details TEXT NOT NULL,
    type ENUM ('INCIDENT','THREAT') 
);


CREATE TABLE `INCIDENT_BY_PRESCRIPTION` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	patient INT NOT NULL,
    details TEXT NOT NULL
);

CREATE TABLE `CLINIC`(
    name VARCHAR(20) NOT NULL PRIMARY KEY 
);

CREATE TABLE `APPOINTMENT` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`date` DATE NOT NULL,
    patient	INT NOT NULL,
    clinician INT NOT NULL,
    clinic VARCHAR(20) NOT NULL,
    `time` TIME NOT NULL,
    `type` ENUM('PRE_ARRANGED','DROP_IN') NOT NULL,
    `status` ENUM('SHOW_UP','NOT_SHOW_UP')
);